# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client\simple_input_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(800, 440)
        Frame.setStyleSheet(_fromUtf8(""))
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_dynamics = QtGui.QFrame(Frame)
        self.frm_dynamics.setGeometry(QtCore.QRect(0, 0, 815, 351))
        self.frm_dynamics.setStyleSheet(_fromUtf8("background-color: #f0f0f0"))
        self.frm_dynamics.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_dynamics.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_dynamics.setObjectName(_fromUtf8("frm_dynamics"))
        self.groupBox = QtGui.QGroupBox(self.frm_dynamics)
        self.groupBox.setGeometry(QtCore.QRect(40, 8, 581, 331))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.sld_x_0 = QtGui.QSlider(self.groupBox)
        self.sld_x_0.setGeometry(QtCore.QRect(60, 40, 22, 200))
        self.sld_x_0.setMinimum(-100)
        self.sld_x_0.setMaximum(100)
        self.sld_x_0.setProperty("value", 0)
        self.sld_x_0.setOrientation(QtCore.Qt.Vertical)
        self.sld_x_0.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sld_x_0.setTickInterval(10)
        self.sld_x_0.setObjectName(_fromUtf8("sld_x_0"))
        self.sld_y_1 = QtGui.QSlider(self.groupBox)
        self.sld_y_1.setGeometry(QtCore.QRect(150, 40, 22, 200))
        self.sld_y_1.setMinimum(-100)
        self.sld_y_1.setMaximum(100)
        self.sld_y_1.setProperty("value", 0)
        self.sld_y_1.setOrientation(QtCore.Qt.Vertical)
        self.sld_y_1.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sld_y_1.setTickInterval(10)
        self.sld_y_1.setObjectName(_fromUtf8("sld_y_1"))
        self.sld_z_2 = QtGui.QSlider(self.groupBox)
        self.sld_z_2.setGeometry(QtCore.QRect(240, 40, 22, 200))
        self.sld_z_2.setMinimum(-100)
        self.sld_z_2.setMaximum(100)
        self.sld_z_2.setProperty("value", 0)
        self.sld_z_2.setOrientation(QtCore.Qt.Vertical)
        self.sld_z_2.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sld_z_2.setTickInterval(10)
        self.sld_z_2.setObjectName(_fromUtf8("sld_z_2"))
        self.sld_roll_3 = QtGui.QSlider(self.groupBox)
        self.sld_roll_3.setGeometry(QtCore.QRect(330, 40, 22, 200))
        self.sld_roll_3.setMinimum(-100)
        self.sld_roll_3.setMaximum(100)
        self.sld_roll_3.setProperty("value", 0)
        self.sld_roll_3.setOrientation(QtCore.Qt.Vertical)
        self.sld_roll_3.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sld_roll_3.setTickInterval(10)
        self.sld_roll_3.setObjectName(_fromUtf8("sld_roll_3"))
        self.sld_pitch_4 = QtGui.QSlider(self.groupBox)
        self.sld_pitch_4.setGeometry(QtCore.QRect(420, 40, 22, 200))
        self.sld_pitch_4.setMinimum(-100)
        self.sld_pitch_4.setMaximum(100)
        self.sld_pitch_4.setProperty("value", 0)
        self.sld_pitch_4.setOrientation(QtCore.Qt.Vertical)
        self.sld_pitch_4.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sld_pitch_4.setTickInterval(10)
        self.sld_pitch_4.setObjectName(_fromUtf8("sld_pitch_4"))
        self.sld_yaw_5 = QtGui.QSlider(self.groupBox)
        self.sld_yaw_5.setGeometry(QtCore.QRect(510, 40, 22, 200))
        self.sld_yaw_5.setMinimum(-100)
        self.sld_yaw_5.setMaximum(100)
        self.sld_yaw_5.setProperty("value", 0)
        self.sld_yaw_5.setOrientation(QtCore.Qt.Vertical)
        self.sld_yaw_5.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sld_yaw_5.setTickInterval(10)
        self.sld_yaw_5.setObjectName(_fromUtf8("sld_yaw_5"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(61, 269, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(150, 270, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(240, 270, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.sld_roll = QtGui.QLabel(self.groupBox)
        self.sld_roll.setGeometry(QtCore.QRect(320, 270, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sld_roll.setFont(font)
        self.sld_roll.setAlignment(QtCore.Qt.AlignCenter)
        self.sld_roll.setObjectName(_fromUtf8("sld_roll"))
        self.sld_pitch = QtGui.QLabel(self.groupBox)
        self.sld_pitch.setGeometry(QtCore.QRect(410, 270, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sld_pitch.setFont(font)
        self.sld_pitch.setAlignment(QtCore.Qt.AlignCenter)
        self.sld_pitch.setObjectName(_fromUtf8("sld_pitch"))
        self.sld_yaw = QtGui.QLabel(self.groupBox)
        self.sld_yaw.setGeometry(QtCore.QRect(500, 270, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sld_yaw.setFont(font)
        self.sld_yaw.setAlignment(QtCore.Qt.AlignCenter)
        self.sld_yaw.setObjectName(_fromUtf8("sld_yaw"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(19, 39, 31, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(16, 228, 41, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 134, 16, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.btn_mid_pos = QtGui.QPushButton(self.frm_dynamics)
        self.btn_mid_pos.setGeometry(QtCore.QRect(690, 130, 75, 23))
        self.btn_mid_pos.setObjectName(_fromUtf8("btn_mid_pos"))

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(_translate("Frame", "Frame", None))
        self.groupBox.setTitle(_translate("Frame", "Levels", None))
        self.label_8.setText(_translate("Frame", "X", None))
        self.label_9.setText(_translate("Frame", "Y", None))
        self.label_10.setText(_translate("Frame", "Z", None))
        self.sld_roll.setText(_translate("Frame", "Roll", None))
        self.sld_pitch.setText(_translate("Frame", "Pitch", None))
        self.sld_yaw.setText(_translate("Frame", "Yaw", None))
        self.label.setText(_translate("Frame", "100%", None))
        self.label_2.setText(_translate("Frame", "-100%", None))
        self.label_3.setText(_translate("Frame", "0", None))
        self.btn_mid_pos.setText(_translate("Frame", "Mid Pos", None))

