# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1028, 959)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 4, 201, 51))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.btn_open = QtGui.QPushButton(self.groupBox)
        self.btn_open.setGeometry(QtCore.QRect(12, 20, 61, 23))
        self.btn_open.setObjectName(_fromUtf8("btn_open"))
        self.cmb_video_fname = QtGui.QComboBox(self.groupBox)
        self.cmb_video_fname.setGeometry(QtCore.QRect(80, 20, 111, 22))
        self.cmb_video_fname.setObjectName(_fromUtf8("cmb_video_fname"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 54, 471, 91))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.btn_play = QtGui.QPushButton(self.groupBox_2)
        self.btn_play.setGeometry(QtCore.QRect(11, 21, 61, 23))
        self.btn_play.setObjectName(_fromUtf8("btn_play"))
        self.btn_pause = QtGui.QPushButton(self.groupBox_2)
        self.btn_pause.setGeometry(QtCore.QRect(80, 21, 61, 23))
        self.btn_pause.setObjectName(_fromUtf8("btn_pause"))
        self.btn_goto_frame = QtGui.QPushButton(self.groupBox_2)
        self.btn_goto_frame.setGeometry(QtCore.QRect(170, 21, 71, 23))
        self.btn_goto_frame.setObjectName(_fromUtf8("btn_goto_frame"))
        self.txt_frame = QtGui.QLineEdit(self.groupBox_2)
        self.txt_frame.setGeometry(QtCore.QRect(250, 22, 51, 20))
        self.txt_frame.setObjectName(_fromUtf8("txt_frame"))
        self.txt_time = QtGui.QLineEdit(self.groupBox_2)
        self.txt_time.setGeometry(QtCore.QRect(410, 22, 51, 20))
        self.txt_time.setObjectName(_fromUtf8("txt_time"))
        self.sld_course_pos = QtGui.QSlider(self.groupBox_2)
        self.sld_course_pos.setGeometry(QtCore.QRect(10, 60, 341, 22))
        self.sld_course_pos.setOrientation(QtCore.Qt.Horizontal)
        self.sld_course_pos.setObjectName(_fromUtf8("sld_course_pos"))
        self.btn_rev = QtGui.QPushButton(self.groupBox_2)
        self.btn_rev.setGeometry(QtCore.QRect(400, 60, 21, 23))
        self.btn_rev.setObjectName(_fromUtf8("btn_rev"))
        self.btn_fwd = QtGui.QPushButton(self.groupBox_2)
        self.btn_fwd.setGeometry(QtCore.QRect(430, 60, 21, 23))
        self.btn_fwd.setObjectName(_fromUtf8("btn_fwd"))
        self.btn_goto_time = QtGui.QPushButton(self.groupBox_2)
        self.btn_goto_time.setGeometry(QtCore.QRect(334, 21, 61, 23))
        self.btn_goto_time.setObjectName(_fromUtf8("btn_goto_time"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(500, 4, 501, 141))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.frame = QtGui.QFrame(self.groupBox_3)
        self.frame.setGeometry(QtCore.QRect(10, 17, 481, 121))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(170, -5, 151, 121))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 6, 47, 20))
        self.label_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.txt_intensity = QtGui.QLineEdit(self.frame_2)
        self.txt_intensity.setGeometry(QtCore.QRect(60, 6, 71, 20))
        self.txt_intensity.setObjectName(_fromUtf8("txt_intensity"))
        self.txt_roll = QtGui.QLineEdit(self.frame_2)
        self.txt_roll.setGeometry(QtCore.QRect(60, 42, 71, 20))
        self.txt_roll.setObjectName(_fromUtf8("txt_roll"))
        self.lbl_roll = QtGui.QLabel(self.frame_2)
        self.lbl_roll.setGeometry(QtCore.QRect(10, 42, 31, 16))
        self.lbl_roll.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_roll.setObjectName(_fromUtf8("lbl_roll"))
        self.lbl_yaw = QtGui.QLabel(self.frame_2)
        self.lbl_yaw.setGeometry(QtCore.QRect(10, 90, 31, 16))
        self.lbl_yaw.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_yaw.setObjectName(_fromUtf8("lbl_yaw"))
        self.txt_pitch = QtGui.QLineEdit(self.frame_2)
        self.txt_pitch.setGeometry(QtCore.QRect(60, 66, 71, 20))
        self.txt_pitch.setObjectName(_fromUtf8("txt_pitch"))
        self.lbl_pitch = QtGui.QLabel(self.frame_2)
        self.lbl_pitch.setGeometry(QtCore.QRect(10, 66, 31, 16))
        self.lbl_pitch.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pitch.setObjectName(_fromUtf8("lbl_pitch"))
        self.txt_yaw = QtGui.QLineEdit(self.frame_2)
        self.txt_yaw.setGeometry(QtCore.QRect(60, 90, 71, 20))
        self.txt_yaw.setObjectName(_fromUtf8("txt_yaw"))
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 5, 131, 111))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.txt_speed = QtGui.QLineEdit(self.frame_3)
        self.txt_speed.setGeometry(QtCore.QRect(50, 10, 71, 20))
        self.txt_speed.setObjectName(_fromUtf8("txt_speed"))
        self.txt_x = QtGui.QLineEdit(self.frame_3)
        self.txt_x.setGeometry(QtCore.QRect(50, 34, 71, 20))
        self.txt_x.setObjectName(_fromUtf8("txt_x"))
        self.lbl_x = QtGui.QLabel(self.frame_3)
        self.lbl_x.setGeometry(QtCore.QRect(20, 34, 16, 16))
        self.lbl_x.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_x.setObjectName(_fromUtf8("lbl_x"))
        self.lbl_z = QtGui.QLabel(self.frame_3)
        self.lbl_z.setGeometry(QtCore.QRect(20, 82, 16, 16))
        self.lbl_z.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_z.setObjectName(_fromUtf8("lbl_z"))
        self.txt_y = QtGui.QLineEdit(self.frame_3)
        self.txt_y.setGeometry(QtCore.QRect(50, 58, 71, 20))
        self.txt_y.setObjectName(_fromUtf8("txt_y"))
        self.lbl_y = QtGui.QLabel(self.frame_3)
        self.lbl_y.setGeometry(QtCore.QRect(20, 58, 16, 16))
        self.lbl_y.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_y.setObjectName(_fromUtf8("lbl_y"))
        self.txt_z = QtGui.QLineEdit(self.frame_3)
        self.txt_z.setGeometry(QtCore.QRect(50, 82, 71, 20))
        self.txt_z.setObjectName(_fromUtf8("txt_z"))
        self.frame_5 = QtGui.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(340, 5, 131, 111))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_14 = QtGui.QLabel(self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.txt_heading = QtGui.QLineEdit(self.frame_5)
        self.txt_heading.setGeometry(QtCore.QRect(60, 10, 71, 20))
        self.txt_heading.setObjectName(_fromUtf8("txt_heading"))
        self.txt_ax = QtGui.QLineEdit(self.frame_5)
        self.txt_ax.setGeometry(QtCore.QRect(60, 34, 71, 20))
        self.txt_ax.setObjectName(_fromUtf8("txt_ax"))
        self.label_15 = QtGui.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(20, 34, 47, 13))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(20, 82, 47, 13))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.txt_ay = QtGui.QLineEdit(self.frame_5)
        self.txt_ay.setGeometry(QtCore.QRect(60, 58, 71, 20))
        self.txt_ay.setObjectName(_fromUtf8("txt_ay"))
        self.label_17 = QtGui.QLabel(self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(20, 58, 47, 13))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.txt_az = QtGui.QLineEdit(self.frame_5)
        self.txt_az.setGeometry(QtCore.QRect(60, 82, 71, 20))
        self.txt_az.setObjectName(_fromUtf8("txt_az"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(20, 357, 981, 561))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.lbl_video_frame = QtGui.QLabel(self.frame_4)
        self.lbl_video_frame.setGeometry(QtCore.QRect(10, 12, 960, 540))
        self.lbl_video_frame.setMinimumSize(QtCore.QSize(960, 540))
        self.lbl_video_frame.setMaximumSize(QtCore.QSize(960, 540))
        self.lbl_video_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_video_frame.setText(_fromUtf8(""))
        self.lbl_video_frame.setObjectName(_fromUtf8("lbl_video_frame"))
        self.lbl_chair_top = QtGui.QLabel(self.frame_4)
        self.lbl_chair_top.setGeometry(QtCore.QRect(890, 10, 81, 91))
        self.lbl_chair_top.setFrameShadow(QtGui.QFrame.Plain)
        self.lbl_chair_top.setLineWidth(1)
        self.lbl_chair_top.setMidLineWidth(0)
        self.lbl_chair_top.setText(_fromUtf8(""))
        self.lbl_chair_top.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_chair_top.setObjectName(_fromUtf8("lbl_chair_top"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 150, 981, 201))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.plotWidget = PlotWidget(self.groupBox_4)
        self.plotWidget.setGeometry(QtCore.QRect(10, 16, 961, 181))
        self.plotWidget.setObjectName(_fromUtf8("plotWidget"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(270, 5, 221, 51))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.btn_serial = QtGui.QPushButton(self.groupBox_5)
        self.btn_serial.setGeometry(QtCore.QRect(12, 20, 61, 23))
        self.btn_serial.setObjectName(_fromUtf8("btn_serial"))
        self.cmb_serial_ports = QtGui.QComboBox(self.groupBox_5)
        self.cmb_serial_ports.setGeometry(QtCore.QRect(130, 20, 71, 22))
        self.cmb_serial_ports.setObjectName(_fromUtf8("cmb_serial_ports"))
        self.lbl_serial_port = QtGui.QLabel(self.groupBox_5)
        self.lbl_serial_port.setGeometry(QtCore.QRect(94, 25, 46, 13))
        self.lbl_serial_port.setObjectName(_fromUtf8("lbl_serial_port"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1028, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Video File", None))
        self.btn_open.setText(_translate("MainWindow", "Open", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Control", None))
        self.btn_play.setText(_translate("MainWindow", "Play", None))
        self.btn_pause.setText(_translate("MainWindow", "Pause", None))
        self.btn_goto_frame.setText(_translate("MainWindow", "Go to Frame", None))
        self.btn_rev.setText(_translate("MainWindow", "<", None))
        self.btn_fwd.setText(_translate("MainWindow", ">", None))
        self.btn_goto_time.setText(_translate("MainWindow", "Go to Time", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Telemetry", None))
        self.label_10.setText(_translate("MainWindow", "Intensity", None))
        self.lbl_roll.setText(_translate("MainWindow", "Roll", None))
        self.lbl_yaw.setText(_translate("MainWindow", "Yaw", None))
        self.lbl_pitch.setText(_translate("MainWindow", "Pitch", None))
        self.label_6.setText(_translate("MainWindow", "Speed", None))
        self.lbl_x.setText(_translate("MainWindow", "X", None))
        self.lbl_z.setText(_translate("MainWindow", "Z", None))
        self.lbl_y.setText(_translate("MainWindow", "Y", None))
        self.label_14.setText(_translate("MainWindow", "Heading", None))
        self.label_15.setText(_translate("MainWindow", "aX", None))
        self.label_16.setText(_translate("MainWindow", "aZ", None))
        self.label_17.setText(_translate("MainWindow", "aY", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Plot", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Model", None))
        self.btn_serial.setText(_translate("MainWindow", "Connect", None))
        self.lbl_serial_port.setText(_translate("MainWindow", "Port", None))

from pyqtgraph import PlotWidget
