# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'echo_handler_gui_defs.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 393)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frm_output = QtWidgets.QFrame(self.centralwidget)
        self.frm_output.setGeometry(QtCore.QRect(0, 0, 791, 351))
        self.frm_output.setStyleSheet("background-color: #f0f0f0")
        self.frm_output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_output.setObjectName("frm_output")
        self.gb_actuator_percent = QtWidgets.QGroupBox(self.frm_output)
        self.gb_actuator_percent.setGeometry(QtCore.QRect(410, 10, 371, 161))
        self.gb_actuator_percent.setObjectName("gb_actuator_percent")
        self.muscle_3 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.muscle_3.setEnabled(False)
        self.muscle_3.setGeometry(QtCore.QRect(40, 90, 200, 16))
        self.muscle_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.muscle_3.setLineWidth(8)
        self.muscle_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.muscle_3.setObjectName("muscle_3")
        self.muscle_4 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.muscle_4.setEnabled(False)
        self.muscle_4.setGeometry(QtCore.QRect(40, 110, 200, 16))
        self.muscle_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.muscle_4.setLineWidth(8)
        self.muscle_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.muscle_4.setObjectName("muscle_4")
        self.muscle_5 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.muscle_5.setEnabled(False)
        self.muscle_5.setGeometry(QtCore.QRect(40, 130, 200, 16))
        self.muscle_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.muscle_5.setLineWidth(8)
        self.muscle_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.muscle_5.setObjectName("muscle_5")
        self.muscle_2 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.muscle_2.setEnabled(False)
        self.muscle_2.setGeometry(QtCore.QRect(40, 70, 200, 16))
        self.muscle_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.muscle_2.setLineWidth(8)
        self.muscle_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.muscle_2.setObjectName("muscle_2")
        self.muscle_1 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.muscle_1.setEnabled(False)
        self.muscle_1.setGeometry(QtCore.QRect(40, 50, 200, 16))
        self.muscle_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.muscle_1.setLineWidth(8)
        self.muscle_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.muscle_1.setObjectName("muscle_1")
        self.muscle_0 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.muscle_0.setEnabled(False)
        self.muscle_0.setGeometry(QtCore.QRect(40, 30, 200, 16))
        self.muscle_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.muscle_0.setLineWidth(8)
        self.muscle_0.setFrameShape(QtWidgets.QFrame.HLine)
        self.muscle_0.setObjectName("muscle_0")
        self.txt_muscle_0 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_0.setGeometry(QtCore.QRect(260, 30, 71, 16))
        self.txt_muscle_0.setObjectName("txt_muscle_0")
        self.txt_muscle_1 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_1.setGeometry(QtCore.QRect(260, 50, 71, 16))
        self.txt_muscle_1.setObjectName("txt_muscle_1")
        self.txt_muscle_2 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_2.setGeometry(QtCore.QRect(260, 70, 71, 16))
        self.txt_muscle_2.setObjectName("txt_muscle_2")
        self.txt_muscle_3 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_3.setGeometry(QtCore.QRect(260, 90, 71, 16))
        self.txt_muscle_3.setObjectName("txt_muscle_3")
        self.txt_muscle_4 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_4.setGeometry(QtCore.QRect(260, 110, 71, 16))
        self.txt_muscle_4.setObjectName("txt_muscle_4")
        self.txt_muscle_5 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_5.setGeometry(QtCore.QRect(260, 130, 71, 16))
        self.txt_muscle_5.setObjectName("txt_muscle_5")
        self.grp_request = QtWidgets.QGroupBox(self.frm_output)
        self.grp_request.setGeometry(QtCore.QRect(40, 10, 141, 251))
        self.grp_request.setObjectName("grp_request")
        self.txt_xform_0 = QtWidgets.QLineEdit(self.grp_request)
        self.txt_xform_0.setGeometry(QtCore.QRect(60, 40, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.txt_xform_0.setFont(font)
        self.txt_xform_0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_xform_0.setObjectName("txt_xform_0")
        self.txt_xform_3 = QtWidgets.QLineEdit(self.grp_request)
        self.txt_xform_3.setGeometry(QtCore.QRect(60, 130, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.txt_xform_3.setFont(font)
        self.txt_xform_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_xform_3.setObjectName("txt_xform_3")
        self.txt_xform_1 = QtWidgets.QLineEdit(self.grp_request)
        self.txt_xform_1.setGeometry(QtCore.QRect(60, 70, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.txt_xform_1.setFont(font)
        self.txt_xform_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_xform_1.setObjectName("txt_xform_1")
        self.txt_xform_2 = QtWidgets.QLineEdit(self.grp_request)
        self.txt_xform_2.setGeometry(QtCore.QRect(60, 100, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.txt_xform_2.setFont(font)
        self.txt_xform_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_xform_2.setObjectName("txt_xform_2")
        self.txt_xform_4 = QtWidgets.QLineEdit(self.grp_request)
        self.txt_xform_4.setGeometry(QtCore.QRect(60, 160, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.txt_xform_4.setFont(font)
        self.txt_xform_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_xform_4.setObjectName("txt_xform_4")
        self.txt_xform_5 = QtWidgets.QLineEdit(self.grp_request)
        self.txt_xform_5.setGeometry(QtCore.QRect(60, 190, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.txt_xform_5.setFont(font)
        self.txt_xform_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_xform_5.setObjectName("txt_xform_5")
        self.label_3 = QtWidgets.QLabel(self.grp_request)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 41, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.grp_request)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 41, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.grp_request)
        self.label_5.setGeometry(QtCore.QRect(10, 190, 41, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.grp_request)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 41, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.grp_request)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 41, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.grp_request)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 41, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.frame = QtWidgets.QFrame(self.frm_output)
        self.frame.setGeometry(QtCore.QRect(208, 10, 181, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.line_10 = QtWidgets.QFrame(self.frame)
        self.line_10.setGeometry(QtCore.QRect(30, 44, 118, 3))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.frame)
        self.line_11.setGeometry(QtCore.QRect(85, 0, 20, 261))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.frame)
        self.line_12.setGeometry(QtCore.QRect(36, 127, 118, 3))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.frame)
        self.line_13.setGeometry(QtCore.QRect(37, 209, 118, 3))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.lbl_front_view = QtWidgets.QLabel(self.frame)
        self.lbl_front_view.setGeometry(QtCore.QRect(49, 10, 90, 70))
        self.lbl_front_view.setText("")
        self.lbl_front_view.setPixmap(QtGui.QPixmap("images/front.png"))
        self.lbl_front_view.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_front_view.setObjectName("lbl_front_view")
        self.lbl_top_view = QtWidgets.QLabel(self.frm_output)
        self.lbl_top_view.setGeometry(QtCore.QRect(258, 180, 90, 80))
        self.lbl_top_view.setText("")
        self.lbl_top_view.setPixmap(QtGui.QPixmap("images/top.png"))
        self.lbl_top_view.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_top_view.setObjectName("lbl_top_view")
        self.lbl_side_view = QtWidgets.QLabel(self.frm_output)
        self.lbl_side_view.setGeometry(QtCore.QRect(258, 102, 90, 70))
        self.lbl_side_view.setText("")
        self.lbl_side_view.setPixmap(QtGui.QPixmap("images/side.png"))
        self.lbl_side_view.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_side_view.setObjectName("lbl_side_view")
        self.bg_load_indices_2 = QtWidgets.QGroupBox(self.frm_output)
        self.bg_load_indices_2.setGeometry(QtCore.QRect(410, 200, 371, 71))
        self.bg_load_indices_2.setObjectName("bg_load_indices_2")
        self.txt_enc_0 = QtWidgets.QLineEdit(self.bg_load_indices_2)
        self.txt_enc_0.setGeometry(QtCore.QRect(50, 30, 31, 20))
        self.txt_enc_0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_enc_0.setObjectName("txt_enc_0")
        self.txt_enc_1 = QtWidgets.QLineEdit(self.bg_load_indices_2)
        self.txt_enc_1.setGeometry(QtCore.QRect(88, 30, 31, 20))
        self.txt_enc_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_enc_1.setObjectName("txt_enc_1")
        self.txt_enc_2 = QtWidgets.QLineEdit(self.bg_load_indices_2)
        self.txt_enc_2.setGeometry(QtCore.QRect(126, 30, 31, 20))
        self.txt_enc_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_enc_2.setObjectName("txt_enc_2")
        self.txt_enc_3 = QtWidgets.QLineEdit(self.bg_load_indices_2)
        self.txt_enc_3.setGeometry(QtCore.QRect(164, 30, 31, 20))
        self.txt_enc_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_enc_3.setObjectName("txt_enc_3")
        self.txt_enc_4 = QtWidgets.QLineEdit(self.bg_load_indices_2)
        self.txt_enc_4.setGeometry(QtCore.QRect(201, 30, 31, 20))
        self.txt_enc_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_enc_4.setObjectName("txt_enc_4")
        self.txt_enc_5 = QtWidgets.QLineEdit(self.bg_load_indices_2)
        self.txt_enc_5.setGeometry(QtCore.QRect(239, 30, 31, 20))
        self.txt_enc_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_enc_5.setObjectName("txt_enc_5")
        self.label_24 = QtWidgets.QLabel(self.bg_load_indices_2)
        self.label_24.setGeometry(QtCore.QRect(10, 32, 31, 16))
        self.label_24.setObjectName("label_24")
        self.groupBox = QtWidgets.QGroupBox(self.frm_output)
        self.groupBox.setGeometry(QtCore.QRect(30, 269, 751, 71))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(14, 3, 261, 61))
        self.groupBox_5.setObjectName("groupBox_5")
        self.cmb_model_port = QtWidgets.QComboBox(self.groupBox_5)
        self.cmb_model_port.setGeometry(QtCore.QRect(180, 30, 71, 22))
        self.cmb_model_port.setObjectName("cmb_model_port")
        self.lbl_model = QtWidgets.QLabel(self.groupBox_5)
        self.lbl_model.setGeometry(QtCore.QRect(200, 10, 31, 16))
        self.lbl_model.setObjectName("lbl_model")
        self.lbl_imu = QtWidgets.QLabel(self.groupBox_5)
        self.lbl_imu.setGeometry(QtCore.QRect(101, 10, 51, 16))
        self.lbl_imu.setObjectName("lbl_imu")
        self.cmb_imu_port = QtWidgets.QComboBox(self.groupBox_5)
        self.cmb_imu_port.setGeometry(QtCore.QRect(90, 30, 71, 22))
        self.cmb_imu_port.setObjectName("cmb_imu_port")
        self.chk_serial_connect = QtWidgets.QCheckBox(self.groupBox_5)
        self.chk_serial_connect.setGeometry(QtCore.QRect(10, 30, 70, 17))
        self.chk_serial_connect.setObjectName("chk_serial_connect")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 10, 451, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(187, 20, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(313, 20, 31, 16))
        self.label_9.setObjectName("label_9")
        self.txt_echo_port = QtWidgets.QLineEdit(self.groupBox_2)
        self.txt_echo_port.setGeometry(QtCore.QRect(60, 20, 41, 20))
        self.txt_echo_port.setObjectName("txt_echo_port")
        self.txt_encoder_ip = QtWidgets.QLineEdit(self.groupBox_2)
        self.txt_encoder_ip.setGeometry(QtCore.QRect(243, 20, 61, 20))
        self.txt_encoder_ip.setObjectName("txt_encoder_ip")
        self.txt_encoder_port = QtWidgets.QLineEdit(self.groupBox_2)
        self.txt_encoder_port.setGeometry(QtCore.QRect(338, 20, 41, 20))
        self.txt_encoder_port.setObjectName("txt_encoder_port")
        self.chk_encoder_connect = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_encoder_connect.setGeometry(QtCore.QRect(385, 20, 61, 17))
        self.chk_encoder_connect.setObjectName("chk_encoder_connect")
        self.chk_echo_connect = QtWidgets.QCheckBox(self.groupBox_2)
        self.chk_echo_connect.setGeometry(QtCore.QRect(110, 20, 70, 17))
        self.chk_echo_connect.setObjectName("chk_echo_connect")
        self.line_14 = QtWidgets.QFrame(self.groupBox_2)
        self.line_14.setGeometry(QtCore.QRect(167, 8, 20, 40))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gb_actuator_percent.setTitle(_translate("MainWindow", "Actuators"))
        self.txt_muscle_0.setText(_translate("MainWindow", "Muscle 0"))
        self.txt_muscle_1.setText(_translate("MainWindow", "Muscle 1"))
        self.txt_muscle_2.setText(_translate("MainWindow", "Muscle 2"))
        self.txt_muscle_3.setText(_translate("MainWindow", "Muscle 3"))
        self.txt_muscle_4.setText(_translate("MainWindow", "Muscle 4"))
        self.txt_muscle_5.setText(_translate("MainWindow", "Muscle 5"))
        self.grp_request.setTitle(_translate("MainWindow", "Request Transform"))
        self.txt_xform_0.setText(_translate("MainWindow", "000"))
        self.txt_xform_3.setText(_translate("MainWindow", "0.00"))
        self.txt_xform_1.setText(_translate("MainWindow", "000"))
        self.txt_xform_2.setText(_translate("MainWindow", "000"))
        self.txt_xform_4.setText(_translate("MainWindow", "0.00"))
        self.txt_xform_5.setText(_translate("MainWindow", "0.00"))
        self.label_3.setText(_translate("MainWindow", "Roll"))
        self.label_4.setText(_translate("MainWindow", "Pitch"))
        self.label_5.setText(_translate("MainWindow", "Yaw"))
        self.label_6.setText(_translate("MainWindow", "Z"))
        self.label_7.setText(_translate("MainWindow", "X"))
        self.label_8.setText(_translate("MainWindow", "Y"))
        self.bg_load_indices_2.setTitle(_translate("MainWindow", "Encoder Values"))
        self.txt_enc_0.setText(_translate("MainWindow", "0"))
        self.txt_enc_1.setText(_translate("MainWindow", "0"))
        self.txt_enc_2.setText(_translate("MainWindow", "0"))
        self.txt_enc_3.setText(_translate("MainWindow", "0"))
        self.txt_enc_4.setText(_translate("MainWindow", "0"))
        self.txt_enc_5.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "mm"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Serial"))
        self.lbl_model.setText(_translate("MainWindow", "Model"))
        self.lbl_imu.setText(_translate("MainWindow", "IMU"))
        self.chk_serial_connect.setText(_translate("MainWindow", "Connect"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Network"))
        self.label.setText(_translate("MainWindow", "Echo Port"))
        self.label_2.setText(_translate("MainWindow", "Encoder IP"))
        self.label_9.setText(_translate("MainWindow", "Port"))
        self.txt_echo_port.setText(_translate("MainWindow", "10020"))
        self.txt_encoder_ip.setText(_translate("MainWindow", "127.0.0.1"))
        self.txt_encoder_port.setText(_translate("MainWindow", "10016"))
        self.chk_encoder_connect.setText(_translate("MainWindow", "Connect"))
        self.chk_echo_connect.setText(_translate("MainWindow", "Connect"))

