# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\PlatformCalibrate\calibration_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True) #enable highdpi scaling
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True) #use highdpi icons

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(515, 631)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 491, 591))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 10, 491, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tb_setup = QtWidgets.QWidget()
        self.tb_setup.setObjectName("tb_setup")
        self.SerialGroupBox = QtWidgets.QGroupBox(self.tb_setup)
        self.SerialGroupBox.setGeometry(QtCore.QRect(30, 10, 371, 241))
        self.SerialGroupBox.setObjectName("SerialGroupBox")
        self.btn_serial_connect = QtWidgets.QPushButton(self.SerialGroupBox)
        self.btn_serial_connect.setGeometry(QtCore.QRect(100, 200, 80, 23))
        self.btn_serial_connect.setMinimumSize(QtCore.QSize(80, 20))
        self.btn_serial_connect.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_serial_connect.setStyleSheet(" background-color: silver;\n"
"color:black;")
        self.btn_serial_connect.setObjectName("btn_serial_connect")
        self.lbl_encoders = QtWidgets.QLabel(self.SerialGroupBox)
        self.lbl_encoders.setGeometry(QtCore.QRect(8, 35, 100, 16))
        self.lbl_encoders.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_encoders.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_encoders.setObjectName("lbl_encoders")
        self.cmb_encoder_port = QtWidgets.QComboBox(self.SerialGroupBox)
        self.cmb_encoder_port.setGeometry(QtCore.QRect(100, 37, 80, 20))
        self.cmb_encoder_port.setMinimumSize(QtCore.QSize(70, 20))
        self.cmb_encoder_port.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cmb_encoder_port.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.cmb_encoder_port.setMinimumContentsLength(15)
        self.cmb_encoder_port.setObjectName("cmb_encoder_port")
        self.lbl_imu = QtWidgets.QLabel(self.SerialGroupBox)
        self.lbl_imu.setGeometry(QtCore.QRect(8, 75, 100, 16))
        self.lbl_imu.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_imu.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_imu.setObjectName("lbl_imu")
        self.cmb_imu_port = QtWidgets.QComboBox(self.SerialGroupBox)
        self.cmb_imu_port.setGeometry(QtCore.QRect(100, 75, 80, 20))
        self.cmb_imu_port.setMinimumSize(QtCore.QSize(70, 20))
        self.cmb_imu_port.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cmb_imu_port.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.cmb_imu_port.setMinimumContentsLength(15)
        self.cmb_imu_port.setObjectName("cmb_imu_port")
        self.lbl_scale = QtWidgets.QLabel(self.SerialGroupBox)
        self.lbl_scale.setGeometry(QtCore.QRect(8, 116, 100, 16))
        self.lbl_scale.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_scale.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_scale.setObjectName("lbl_scale")
        self.cmb_scale_port = QtWidgets.QComboBox(self.SerialGroupBox)
        self.cmb_scale_port.setGeometry(QtCore.QRect(100, 116, 80, 20))
        self.cmb_scale_port.setMinimumSize(QtCore.QSize(70, 0))
        self.cmb_scale_port.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cmb_scale_port.setObjectName("cmb_scale_port")
        self.lbl_model = QtWidgets.QLabel(self.SerialGroupBox)
        self.lbl_model.setGeometry(QtCore.QRect(8, 155, 100, 16))
        self.lbl_model.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_model.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_model.setObjectName("lbl_model")
        self.cmb_model_port = QtWidgets.QComboBox(self.SerialGroupBox)
        self.cmb_model_port.setGeometry(QtCore.QRect(100, 155, 80, 20))
        self.cmb_model_port.setMinimumSize(QtCore.QSize(70, 0))
        self.cmb_model_port.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cmb_model_port.setObjectName("cmb_model_port")
        self.chk_hold = QtWidgets.QCheckBox(self.SerialGroupBox)
        self.chk_hold.setGeometry(QtCore.QRect(298, 118, 44, 17))
        self.chk_hold.setObjectName("chk_hold")
        self.chk_model_enabled = QtWidgets.QCheckBox(self.SerialGroupBox)
        self.chk_model_enabled.setGeometry(QtCore.QRect(200, 156, 70, 17))
        self.chk_model_enabled.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chk_model_enabled.setObjectName("chk_model_enabled")
        self.label_20 = QtWidgets.QLabel(self.tb_setup)
        self.label_20.setGeometry(QtCore.QRect(226, 126, 39, 20))
        self.label_20.setMinimumSize(QtCore.QSize(0, 20))
        self.label_20.setObjectName("label_20")
        self.txt_weight_2 = QtWidgets.QLineEdit(self.tb_setup)
        self.txt_weight_2.setGeometry(QtCore.QRect(268, 126, 50, 20))
        self.txt_weight_2.setMinimumSize(QtCore.QSize(0, 20))
        self.txt_weight_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_weight_2.setObjectName("txt_weight_2")
        self.tabWidget.addTab(self.tb_setup, "")
        self.tb_calibrate = QtWidgets.QWidget()
        self.tb_calibrate.setObjectName("tb_calibrate")
        self.PositionGroupBox = QtWidgets.QGroupBox(self.tb_calibrate)
        self.PositionGroupBox.setGeometry(QtCore.QRect(6, 230, 471, 51))
        self.PositionGroupBox.setMinimumSize(QtCore.QSize(400, 0))
        self.PositionGroupBox.setObjectName("PositionGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.PositionGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_pos_0 = QtWidgets.QLineEdit(self.PositionGroupBox)
        self.txt_pos_0.setMinimumSize(QtCore.QSize(0, 20))
        self.txt_pos_0.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_pos_0.setObjectName("txt_pos_0")
        self.horizontalLayout.addWidget(self.txt_pos_0)
        self.txt_pos_1 = QtWidgets.QLineEdit(self.PositionGroupBox)
        self.txt_pos_1.setMinimumSize(QtCore.QSize(0, 20))
        self.txt_pos_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_pos_1.setObjectName("txt_pos_1")
        self.horizontalLayout.addWidget(self.txt_pos_1)
        self.txt_pos_2 = QtWidgets.QLineEdit(self.PositionGroupBox)
        self.txt_pos_2.setMinimumSize(QtCore.QSize(0, 20))
        self.txt_pos_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_pos_2.setObjectName("txt_pos_2")
        self.horizontalLayout.addWidget(self.txt_pos_2)
        self.txt_pos_3 = QtWidgets.QLineEdit(self.PositionGroupBox)
        self.txt_pos_3.setMinimumSize(QtCore.QSize(0, 20))
        self.txt_pos_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_pos_3.setObjectName("txt_pos_3")
        self.horizontalLayout.addWidget(self.txt_pos_3)
        self.txt_pos_4 = QtWidgets.QLineEdit(self.PositionGroupBox)
        self.txt_pos_4.setMinimumSize(QtCore.QSize(0, 20))
        self.txt_pos_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_pos_4.setObjectName("txt_pos_4")
        self.horizontalLayout.addWidget(self.txt_pos_4)
        self.txt_pos_5 = QtWidgets.QLineEdit(self.PositionGroupBox)
        self.txt_pos_5.setMinimumSize(QtCore.QSize(0, 20))
        self.txt_pos_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_pos_5.setObjectName("txt_pos_5")
        self.horizontalLayout.addWidget(self.txt_pos_5)
        self.CalibrateGroupBox = QtWidgets.QGroupBox(self.tb_calibrate)
        self.CalibrateGroupBox.setGeometry(QtCore.QRect(10, 10, 471, 111))
        self.CalibrateGroupBox.setMinimumSize(QtCore.QSize(200, 0))
        self.CalibrateGroupBox.setObjectName("CalibrateGroupBox")
        self.btn_calibrate = QtWidgets.QPushButton(self.CalibrateGroupBox)
        self.btn_calibrate.setGeometry(QtCore.QRect(12, 24, 75, 23))
        self.btn_calibrate.setObjectName("btn_calibrate")
        self.label_7 = QtWidgets.QLabel(self.CalibrateGroupBox)
        self.label_7.setGeometry(QtCore.QRect(121, 28, 91, 16))
        self.label_7.setObjectName("label_7")
        self.txt_steps = QtWidgets.QLineEdit(self.CalibrateGroupBox)
        self.txt_steps.setGeometry(QtCore.QRect(221, 25, 30, 20))
        self.txt_steps.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_steps.setObjectName("txt_steps")
        self.label_9 = QtWidgets.QLabel(self.CalibrateGroupBox)
        self.label_9.setGeometry(QtCore.QRect(277, 27, 51, 16))
        self.label_9.setObjectName("label_9")
        self.txt_step_delay_ms = QtWidgets.QLineEdit(self.CalibrateGroupBox)
        self.txt_step_delay_ms.setGeometry(QtCore.QRect(330, 25, 40, 20))
        self.txt_step_delay_ms.setMinimumSize(QtCore.QSize(30, 0))
        self.txt_step_delay_ms.setMaximumSize(QtCore.QSize(40, 16777215))
        self.txt_step_delay_ms.setObjectName("txt_step_delay_ms")
        self.label_8 = QtWidgets.QLabel(self.CalibrateGroupBox)
        self.label_8.setGeometry(QtCore.QRect(387, 26, 40, 16))
        self.label_8.setObjectName("label_8")
        self.txt_repeats = QtWidgets.QLineEdit(self.CalibrateGroupBox)
        self.txt_repeats.setGeometry(QtCore.QRect(431, 25, 30, 20))
        self.txt_repeats.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_repeats.setObjectName("txt_repeats")
        self.txt_weight = QtWidgets.QLineEdit(self.CalibrateGroupBox)
        self.txt_weight.setGeometry(QtCore.QRect(58, 72, 50, 20))
        self.txt_weight.setMinimumSize(QtCore.QSize(0, 20))
        self.txt_weight.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_weight.setObjectName("txt_weight")
        self.label_10 = QtWidgets.QLabel(self.CalibrateGroupBox)
        self.label_10.setGeometry(QtCore.QRect(14, 73, 37, 20))
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setObjectName("label_10")
        self.txt_p_to_d_fname = QtWidgets.QLineEdit(self.CalibrateGroupBox)
        self.txt_p_to_d_fname.setGeometry(QtCore.QRect(279, 72, 75, 20))
        self.txt_p_to_d_fname.setMinimumSize(QtCore.QSize(0, 20))
        self.txt_p_to_d_fname.setMaximumSize(QtCore.QSize(80, 16777215))
        self.txt_p_to_d_fname.setObjectName("txt_p_to_d_fname")
        self.label_22 = QtWidgets.QLabel(self.CalibrateGroupBox)
        self.label_22.setGeometry(QtCore.QRect(132, 74, 141, 16))
        self.label_22.setObjectName("label_22")
        self.btn_save_step_data = QtWidgets.QPushButton(self.CalibrateGroupBox)
        self.btn_save_step_data.setGeometry(QtCore.QRect(370, 70, 75, 23))
        self.btn_save_step_data.setObjectName("btn_save_step_data")
        self.label_7.raise_()
        self.label_8.raise_()
        self.btn_calibrate.raise_()
        self.txt_repeats.raise_()
        self.label_9.raise_()
        self.txt_steps.raise_()
        self.txt_step_delay_ms.raise_()
        self.txt_weight.raise_()
        self.label_10.raise_()
        self.txt_p_to_d_fname.raise_()
        self.label_22.raise_()
        self.btn_save_step_data.raise_()
        self.groupBox_4 = QtWidgets.QGroupBox(self.tb_calibrate)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 130, 471, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.chk_combined_chart = QtWidgets.QCheckBox(self.groupBox_4)
        self.chk_combined_chart.setGeometry(QtCore.QRect(81, 59, 114, 17))
        self.chk_combined_chart.setChecked(True)
        self.chk_combined_chart.setObjectName("chk_combined_chart")
        self.chk_individual_chart = QtWidgets.QCheckBox(self.groupBox_4)
        self.chk_individual_chart.setGeometry(QtCore.QRect(210, 59, 116, 17))
        self.chk_individual_chart.setChecked(True)
        self.chk_individual_chart.setObjectName("chk_individual_chart")
        self.chk_std_dev = QtWidgets.QCheckBox(self.groupBox_4)
        self.chk_std_dev.setGeometry(QtCore.QRect(360, 59, 61, 17))
        self.chk_std_dev.setChecked(True)
        self.chk_std_dev.setObjectName("chk_std_dev")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(10, 59, 61, 16))
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(130, 21, 141, 20))
        self.label_19.setObjectName("label_19")
        self.txt_d_to_p_fname_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.txt_d_to_p_fname_2.setGeometry(QtCore.QRect(279, 22, 75, 20))
        self.txt_d_to_p_fname_2.setObjectName("txt_d_to_p_fname_2")
        self.btn_create_d_to_p = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_create_d_to_p.setGeometry(QtCore.QRect(370, 21, 75, 23))
        self.btn_create_d_to_p.setObjectName("btn_create_d_to_p")
        self.tabWidget.addTab(self.tb_calibrate, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 10, 151, 251))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lst_p_to_d = QtWidgets.QListWidget(self.groupBox_5)
        self.lst_p_to_d.setGeometry(QtCore.QRect(10, 20, 131, 192))
        self.lst_p_to_d.setObjectName("lst_p_to_d")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(200, 10, 151, 251))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lst_d_to_p = QtWidgets.QListWidget(self.groupBox_6)
        self.lst_d_to_p.setGeometry(QtCore.QRect(10, 20, 131, 192))
        self.lst_d_to_p.setObjectName("lst_d_to_p")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(360, 10, 111, 111))
        self.groupBox_7.setObjectName("groupBox_7")
        self.btn_merge_d_to_p = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_merge_d_to_p.setGeometry(QtCore.QRect(20, 80, 75, 23))
        self.btn_merge_d_to_p.setObjectName("btn_merge_d_to_p")
        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setGeometry(QtCore.QRect(38, 53, 46, 13))
        self.label_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_18.setObjectName("label_18")
        self.txt_merged_d_to_p_fname = QtWidgets.QLineEdit(self.groupBox_7)
        self.txt_merged_d_to_p_fname.setGeometry(QtCore.QRect(6, 30, 101, 20))
        self.txt_merged_d_to_p_fname.setObjectName("txt_merged_d_to_p_fname")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 110, 431, 161))
        self.groupBox.setObjectName("groupBox")
        self.btn_run_lookup = QtWidgets.QPushButton(self.groupBox)
        self.btn_run_lookup.setGeometry(QtCore.QRect(20, 60, 75, 23))
        self.btn_run_lookup.setObjectName("btn_run_lookup")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 100, 61, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 71, 16))
        self.label_12.setObjectName("label_12")
        self.txt_up_index = QtWidgets.QLineEdit(self.groupBox)
        self.txt_up_index.setGeometry(QtCore.QRect(100, 100, 91, 20))
        self.txt_up_index.setObjectName("txt_up_index")
        self.txt_down_index = QtWidgets.QLineEdit(self.groupBox)
        self.txt_down_index.setGeometry(QtCore.QRect(100, 130, 91, 20))
        self.txt_down_index.setObjectName("txt_down_index")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label_13.setObjectName("label_13")
        self.txt_up_pressure = QtWidgets.QLineEdit(self.groupBox)
        self.txt_up_pressure.setGeometry(QtCore.QRect(82, 30, 51, 20))
        self.txt_up_pressure.setObjectName("txt_up_pressure")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(157, 31, 71, 16))
        self.label_14.setObjectName("label_14")
        self.txt_down_pressure = QtWidgets.QLineEdit(self.groupBox)
        self.txt_down_pressure.setGeometry(QtCore.QRect(238, 30, 51, 20))
        self.txt_down_pressure.setObjectName("txt_down_pressure")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(328, 31, 21, 16))
        self.label_15.setObjectName("label_15")
        self.txt_lookup_dur = QtWidgets.QLineEdit(self.groupBox)
        self.txt_lookup_dur.setGeometry(QtCore.QRect(356, 30, 51, 20))
        self.txt_lookup_dur.setObjectName("txt_lookup_dur")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 231, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btn_load_d_to_p = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_load_d_to_p.setGeometry(QtCore.QRect(30, 50, 71, 23))
        self.btn_load_d_to_p.setObjectName("btn_load_d_to_p")
        self.txt_nbr_indices = QtWidgets.QLineEdit(self.groupBox_2)
        self.txt_nbr_indices.setGeometry(QtCore.QRect(170, 50, 41, 20))
        self.txt_nbr_indices.setObjectName("txt_nbr_indices")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(114, 52, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_2.setObjectName("label_2")
        self.txt_d_to_p_fname = QtWidgets.QLineEdit(self.groupBox_2)
        self.txt_d_to_p_fname.setGeometry(QtCore.QRect(100, 20, 113, 20))
        self.txt_d_to_p_fname.setObjectName("txt_d_to_p_fname")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 10, 181, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.chk_delta_capture = QtWidgets.QCheckBox(self.groupBox_3)
        self.chk_delta_capture.setGeometry(QtCore.QRect(20, 54, 70, 17))
        self.chk_delta_capture.setObjectName("chk_delta_capture")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_16.setObjectName("label_16")
        self.txt_delta_fname = QtWidgets.QLineEdit(self.groupBox_3)
        self.txt_delta_fname.setGeometry(QtCore.QRect(52, 20, 121, 20))
        self.txt_delta_fname.setObjectName("txt_delta_fname")
        self.tabWidget.addTab(self.tab, "")
        self.tb_move = QtWidgets.QWidget()
        self.tb_move.setObjectName("tb_move")
        self.MoveGroupBox = QtWidgets.QGroupBox(self.tb_move)
        self.MoveGroupBox.setGeometry(QtCore.QRect(10, 20, 465, 121))
        self.MoveGroupBox.setObjectName("MoveGroupBox")
        self.frame_3 = QtWidgets.QFrame(self.MoveGroupBox)
        self.frame_3.setGeometry(QtCore.QRect(20, 17, 411, 41))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.rb_X = QtWidgets.QRadioButton(self.frame_3)
        self.rb_X.setGeometry(QtCore.QRect(11, 1, 60, 20))
        self.rb_X.setMinimumSize(QtCore.QSize(60, 20))
        self.rb_X.setMaximumSize(QtCore.QSize(60, 16777215))
        self.rb_X.setObjectName("rb_X")
        self.rb_Y = QtWidgets.QRadioButton(self.frame_3)
        self.rb_Y.setGeometry(QtCore.QRect(77, 1, 60, 20))
        self.rb_Y.setMinimumSize(QtCore.QSize(60, 20))
        self.rb_Y.setMaximumSize(QtCore.QSize(60, 16777215))
        self.rb_Y.setObjectName("rb_Y")
        self.rb_Z = QtWidgets.QRadioButton(self.frame_3)
        self.rb_Z.setGeometry(QtCore.QRect(143, 1, 60, 20))
        self.rb_Z.setMinimumSize(QtCore.QSize(60, 20))
        self.rb_Z.setMaximumSize(QtCore.QSize(60, 16777215))
        self.rb_Z.setChecked(True)
        self.rb_Z.setObjectName("rb_Z")
        self.rb_Roll = QtWidgets.QRadioButton(self.frame_3)
        self.rb_Roll.setGeometry(QtCore.QRect(209, 1, 60, 20))
        self.rb_Roll.setMinimumSize(QtCore.QSize(60, 20))
        self.rb_Roll.setMaximumSize(QtCore.QSize(60, 16777215))
        self.rb_Roll.setObjectName("rb_Roll")
        self.rb_Pitch = QtWidgets.QRadioButton(self.frame_3)
        self.rb_Pitch.setGeometry(QtCore.QRect(275, 1, 60, 20))
        self.rb_Pitch.setMinimumSize(QtCore.QSize(60, 20))
        self.rb_Pitch.setMaximumSize(QtCore.QSize(60, 16777215))
        self.rb_Pitch.setObjectName("rb_Pitch")
        self.rb_Yaw = QtWidgets.QRadioButton(self.frame_3)
        self.rb_Yaw.setGeometry(QtCore.QRect(341, 1, 60, 20))
        self.rb_Yaw.setMinimumSize(QtCore.QSize(60, 20))
        self.rb_Yaw.setMaximumSize(QtCore.QSize(60, 16777215))
        self.rb_Yaw.setObjectName("rb_Yaw")
        self.sld_percent = QtWidgets.QSlider(self.MoveGroupBox)
        self.sld_percent.setGeometry(QtCore.QRect(80, 58, 341, 22))
        self.sld_percent.setMinimum(-100)
        self.sld_percent.setMaximum(100)
        self.sld_percent.setProperty("value", 0)
        self.sld_percent.setOrientation(QtCore.Qt.Horizontal)
        self.sld_percent.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sld_percent.setObjectName("sld_percent")
        self.label_3 = QtWidgets.QLabel(self.MoveGroupBox)
        self.label_3.setGeometry(QtCore.QRect(228, 87, 46, 13))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.MoveGroupBox)
        self.label_5.setGeometry(QtCore.QRect(63, 87, 46, 13))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.MoveGroupBox)
        self.label_6.setGeometry(QtCore.QRect(393, 87, 46, 13))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.MoveGroupBox)
        self.label.setGeometry(QtCore.QRect(228, 101, 46, 13))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_move = QtWidgets.QPushButton(self.MoveGroupBox)
        self.btn_move.setGeometry(QtCore.QRect(18, 54, 41, 23))
        self.btn_move.setObjectName("btn_move")
        self.RideGroupBox = QtWidgets.QGroupBox(self.tb_move)
        self.RideGroupBox.setGeometry(QtCore.QRect(10, 200, 471, 77))
        self.RideGroupBox.setObjectName("RideGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.RideGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_ride = QtWidgets.QPushButton(self.RideGroupBox)
        self.btn_ride.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_ride.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_ride.setObjectName("btn_ride")
        self.horizontalLayout_3.addWidget(self.btn_ride)
        self.cmb_ride = QtWidgets.QComboBox(self.RideGroupBox)
        self.cmb_ride.setMinimumSize(QtCore.QSize(100, 0))
        self.cmb_ride.setObjectName("cmb_ride")
        self.horizontalLayout_3.addWidget(self.cmb_ride)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.lbl_ride_action = QtWidgets.QLabel(self.RideGroupBox)
        self.lbl_ride_action.setMinimumSize(QtCore.QSize(240, 20))
        self.lbl_ride_action.setMaximumSize(QtCore.QSize(140, 16777215))
        self.lbl_ride_action.setObjectName("lbl_ride_action")
        self.horizontalLayout_3.addWidget(self.lbl_ride_action)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.DataGroupBox = QtWidgets.QGroupBox(self.tb_move)
        self.DataGroupBox.setGeometry(QtCore.QRect(10, 140, 475, 58))
        self.DataGroupBox.setObjectName("DataGroupBox")
        self.btn_start_capture = QtWidgets.QPushButton(self.DataGroupBox)
        self.btn_start_capture.setGeometry(QtCore.QRect(11, 24, 60, 23))
        self.btn_start_capture.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_start_capture.setObjectName("btn_start_capture")
        self.txt_weight_1 = QtWidgets.QLineEdit(self.DataGroupBox)
        self.txt_weight_1.setGeometry(QtCore.QRect(166, 25, 50, 20))
        self.txt_weight_1.setMinimumSize(QtCore.QSize(0, 20))
        self.txt_weight_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_weight_1.setObjectName("txt_weight_1")
        self.label_21 = QtWidgets.QLabel(self.DataGroupBox)
        self.label_21.setGeometry(QtCore.QRect(123, 24, 37, 20))
        self.label_21.setMinimumSize(QtCore.QSize(0, 20))
        self.label_21.setObjectName("label_21")
        self.btn_save_raw = QtWidgets.QPushButton(self.DataGroupBox)
        self.btn_save_raw.setGeometry(QtCore.QRect(318, 24, 60, 23))
        self.btn_save_raw.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_save_raw.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_save_raw.setObjectName("btn_save_raw")
        self.txt_raw_data_fname = QtWidgets.QLineEdit(self.DataGroupBox)
        self.txt_raw_data_fname.setGeometry(QtCore.QRect(384, 25, 71, 20))
        self.txt_raw_data_fname.setMinimumSize(QtCore.QSize(0, 20))
        self.txt_raw_data_fname.setMaximumSize(QtCore.QSize(80, 16777215))
        self.txt_raw_data_fname.setObjectName("txt_raw_data_fname")
        self.tabWidget.addTab(self.tb_move, "")
        self.ProgressGroupBox = QtWidgets.QGroupBox(self.frame)
        self.ProgressGroupBox.setGeometry(QtCore.QRect(0, 320, 491, 51))
        self.ProgressGroupBox.setObjectName("ProgressGroupBox")
        self.progressBar = QtWidgets.QProgressBar(self.ProgressGroupBox)
        self.progressBar.setGeometry(QtCore.QRect(20, 17, 451, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 520, 471, 61))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btn_estop = QtWidgets.QPushButton(self.frame_2)
        self.btn_estop.setGeometry(QtCore.QRect(160, 10, 151, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_estop.setFont(font)
        self.btn_estop.setStyleSheet("QPushButton {\n"
"    color: yellow;\n"
"    border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888,\n"
"        );\n"
"    padding: 5px;\n"
"    background-color: red;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    background-color: red;\n"
"   color: white;\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.btn_estop.setObjectName("btn_estop")
        self.chk_festo_actuals = QtWidgets.QCheckBox(self.frame_2)
        self.chk_festo_actuals.setGeometry(QtCore.QRect(-4, 20, 131, 20))
        self.chk_festo_actuals.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chk_festo_actuals.setObjectName("chk_festo_actuals")
        self.gb_actuator_percent = QtWidgets.QGroupBox(self.frame)
        self.gb_actuator_percent.setGeometry(QtCore.QRect(10, 370, 471, 151))
        self.gb_actuator_percent.setObjectName("gb_actuator_percent")
        self.muscle_3 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.muscle_3.setEnabled(False)
        self.muscle_3.setGeometry(QtCore.QRect(79, 80, 300, 20))
        self.muscle_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.muscle_3.setLineWidth(8)
        self.muscle_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.muscle_3.setObjectName("muscle_3")
        self.muscle_4 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.muscle_4.setEnabled(False)
        self.muscle_4.setGeometry(QtCore.QRect(79, 100, 300, 20))
        self.muscle_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.muscle_4.setLineWidth(8)
        self.muscle_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.muscle_4.setObjectName("muscle_4")
        self.muscle_5 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.muscle_5.setEnabled(False)
        self.muscle_5.setGeometry(QtCore.QRect(79, 120, 300, 20))
        self.muscle_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.muscle_5.setLineWidth(8)
        self.muscle_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.muscle_5.setObjectName("muscle_5")
        self.muscle_2 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.muscle_2.setEnabled(False)
        self.muscle_2.setGeometry(QtCore.QRect(79, 60, 300, 20))
        self.muscle_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.muscle_2.setLineWidth(8)
        self.muscle_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.muscle_2.setObjectName("muscle_2")
        self.muscle_1 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.muscle_1.setEnabled(False)
        self.muscle_1.setGeometry(QtCore.QRect(79, 40, 300, 20))
        self.muscle_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.muscle_1.setLineWidth(8)
        self.muscle_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.muscle_1.setObjectName("muscle_1")
        self.muscle_0 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.muscle_0.setEnabled(False)
        self.muscle_0.setGeometry(QtCore.QRect(79, 20, 300, 20))
        self.muscle_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.muscle_0.setLineWidth(8)
        self.muscle_0.setFrameShape(QtWidgets.QFrame.HLine)
        self.muscle_0.setObjectName("muscle_0")
        self.txt_muscle_0 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_0.setGeometry(QtCore.QRect(401, 22, 46, 13))
        self.txt_muscle_0.setObjectName("txt_muscle_0")
        self.txt_muscle_1 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_1.setGeometry(QtCore.QRect(401, 42, 46, 13))
        self.txt_muscle_1.setObjectName("txt_muscle_1")
        self.txt_muscle_2 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_2.setGeometry(QtCore.QRect(401, 62, 46, 13))
        self.txt_muscle_2.setObjectName("txt_muscle_2")
        self.txt_muscle_3 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_3.setGeometry(QtCore.QRect(401, 82, 46, 13))
        self.txt_muscle_3.setObjectName("txt_muscle_3")
        self.txt_muscle_4 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_4.setGeometry(QtCore.QRect(401, 102, 46, 13))
        self.txt_muscle_4.setObjectName("txt_muscle_4")
        self.txt_muscle_5 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_5.setGeometry(QtCore.QRect(401, 122, 46, 13))
        self.txt_muscle_5.setObjectName("txt_muscle_5")
        self.txt_muscle_6 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_6.setGeometry(QtCore.QRect(10, 120, 46, 13))
        self.txt_muscle_6.setObjectName("txt_muscle_6")
        self.txt_muscle_7 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_7.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.txt_muscle_7.setObjectName("txt_muscle_7")
        self.txt_muscle_8 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_8.setGeometry(QtCore.QRect(10, 40, 46, 13))
        self.txt_muscle_8.setObjectName("txt_muscle_8")
        self.txt_muscle_9 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_9.setGeometry(QtCore.QRect(10, 80, 46, 13))
        self.txt_muscle_9.setObjectName("txt_muscle_9")
        self.txt_muscle_10 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_10.setGeometry(QtCore.QRect(10, 100, 46, 13))
        self.txt_muscle_10.setObjectName("txt_muscle_10")
        self.txt_muscle_11 = QtWidgets.QLabel(self.gb_actuator_percent)
        self.txt_muscle_11.setGeometry(QtCore.QRect(10, 60, 46, 13))
        self.txt_muscle_11.setObjectName("txt_muscle_11")
        self.actual_0 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.actual_0.setEnabled(False)
        self.actual_0.setGeometry(QtCore.QRect(79, 34, 300, 2))
        self.actual_0.setStyleSheet("color: rgb(255, 0, 0)")
        self.actual_0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.actual_0.setLineWidth(2)
        self.actual_0.setFrameShape(QtWidgets.QFrame.HLine)
        self.actual_0.setObjectName("actual_0")
        self.actual_4 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.actual_4.setEnabled(False)
        self.actual_4.setGeometry(QtCore.QRect(79, 114, 300, 2))
        self.actual_4.setStyleSheet("color: rgb(255, 0, 0)")
        self.actual_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.actual_4.setLineWidth(2)
        self.actual_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.actual_4.setObjectName("actual_4")
        self.actual_2 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.actual_2.setEnabled(False)
        self.actual_2.setGeometry(QtCore.QRect(79, 74, 300, 2))
        self.actual_2.setStyleSheet("color: rgb(255, 0, 0)")
        self.actual_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.actual_2.setLineWidth(2)
        self.actual_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.actual_2.setObjectName("actual_2")
        self.actual_3 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.actual_3.setEnabled(False)
        self.actual_3.setGeometry(QtCore.QRect(79, 94, 300, 2))
        self.actual_3.setStyleSheet("color: rgb(255, 0, 0)")
        self.actual_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.actual_3.setLineWidth(2)
        self.actual_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.actual_3.setObjectName("actual_3")
        self.actual_1 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.actual_1.setEnabled(False)
        self.actual_1.setGeometry(QtCore.QRect(80, 54, 300, 2))
        self.actual_1.setStyleSheet("color: rgb(255, 0, 0)")
        self.actual_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.actual_1.setLineWidth(2)
        self.actual_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.actual_1.setObjectName("actual_1")
        self.actual_5 = QtWidgets.QFrame(self.gb_actuator_percent)
        self.actual_5.setEnabled(False)
        self.actual_5.setGeometry(QtCore.QRect(79, 134, 300, 2))
        self.actual_5.setStyleSheet("color: rgb(255, 0, 0)")
        self.actual_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.actual_5.setLineWidth(2)
        self.actual_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.actual_5.setObjectName("actual_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Platform Test"))
        self.SerialGroupBox.setTitle(_translate("MainWindow", "Comms"))
        self.btn_serial_connect.setText(_translate("MainWindow", "    Connect    "))
        self.lbl_encoders.setText(_translate("MainWindow", "Encoders"))
        self.lbl_imu.setText(_translate("MainWindow", "IMU"))
        self.lbl_scale.setText(_translate("MainWindow", "Scale"))
        self.lbl_model.setText(_translate("MainWindow", "Servo Model"))
        self.chk_hold.setText(_translate("MainWindow", "Hold"))
        self.chk_model_enabled.setText(_translate("MainWindow", "Enabled"))
        self.label_20.setText(_translate("MainWindow", "Reading"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tb_setup), _translate("MainWindow", "Setup"))
        self.PositionGroupBox.setTitle(_translate("MainWindow", "Encoder Readings"))
        self.CalibrateGroupBox.setTitle(_translate("MainWindow", "Create Pressure to Distance file"))
        self.btn_calibrate.setText(_translate("MainWindow", "Start"))
        self.label_7.setText(_translate("MainWindow", "Nbr Pressure Steps"))
        self.label_9.setText(_translate("MainWindow", "Delay (ms)"))
        self.label_8.setText(_translate("MainWindow", "Repeats"))
        self.label_10.setText(_translate("MainWindow", "Load kg"))
        self.label_22.setText(_translate("MainWindow", "Pressure to distance filename"))
        self.btn_save_step_data.setText(_translate("MainWindow", "Save"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Create Distance to Pressure file"))
        self.chk_combined_chart.setText(_translate("MainWindow", "Combined readings"))
        self.chk_individual_chart.setText(_translate("MainWindow", " Individual readings"))
        self.chk_std_dev.setText(_translate("MainWindow", "Std Dev"))
        self.label_17.setText(_translate("MainWindow", "Show Charts"))
        self.label_19.setText(_translate("MainWindow", "Distance to pressure filename"))
        self.btn_create_d_to_p.setText(_translate("MainWindow", "Process"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tb_calibrate), _translate("MainWindow", "Calibrate"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Pressure to Distance files"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Distance to Pressure files"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Merge D to P profiles"))
        self.btn_merge_d_to_p.setText(_translate("MainWindow", "Merge"))
        self.label_18.setText(_translate("MainWindow", "File path"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Data"))
        self.groupBox.setTitle(_translate("MainWindow", "Select up and down profiles closest to current load"))
        self.btn_run_lookup.setText(_translate("MainWindow", "Run"))
        self.label_11.setText(_translate("MainWindow", "Up Indices"))
        self.label_12.setText(_translate("MainWindow", "Down Indices"))
        self.label_13.setText(_translate("MainWindow", "Up Pressure"))
        self.label_14.setText(_translate("MainWindow", "Down Pressure"))
        self.label_15.setText(_translate("MainWindow", "Dur"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Load Distance to Pressure Profiles"))
        self.btn_load_d_to_p.setText(_translate("MainWindow", "Load"))
        self.label_4.setText(_translate("MainWindow", "Nbr Indices"))
        self.label_2.setText(_translate("MainWindow", "D-to-P filename"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Capture Distance Deltas"))
        self.chk_delta_capture.setText(_translate("MainWindow", "Capture"))
        self.label_16.setText(_translate("MainWindow", "Fname"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Profiles"))
        self.MoveGroupBox.setTitle(_translate("MainWindow", "Movement"))
        self.rb_X.setText(_translate("MainWindow", "X"))
        self.rb_Y.setText(_translate("MainWindow", "Y"))
        self.rb_Z.setText(_translate("MainWindow", "Z"))
        self.rb_Roll.setText(_translate("MainWindow", "Roll"))
        self.rb_Pitch.setText(_translate("MainWindow", "Pitch"))
        self.rb_Yaw.setText(_translate("MainWindow", "Yaw"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "-100"))
        self.label_6.setText(_translate("MainWindow", "100"))
        self.label.setText(_translate("MainWindow", "Percent"))
        self.btn_move.setText(_translate("MainWindow", "Move"))
        self.RideGroupBox.setTitle(_translate("MainWindow", "Ride Control"))
        self.btn_ride.setText(_translate("MainWindow", "Start"))
        self.lbl_ride_action.setText(_translate("MainWindow", "Ride Not Active"))
        self.DataGroupBox.setTitle(_translate("MainWindow", "Data  Capture"))
        self.btn_start_capture.setText(_translate("MainWindow", "Capture"))
        self.label_21.setText(_translate("MainWindow", "Load kg"))
        self.btn_save_raw.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tb_move), _translate("MainWindow", "Move"))
        self.ProgressGroupBox.setTitle(_translate("MainWindow", "Progress"))
        self.btn_estop.setText(_translate("MainWindow", "Stop"))
        self.chk_festo_actuals.setText(_translate("MainWindow", "Show Festo response"))
        self.gb_actuator_percent.setTitle(_translate("MainWindow", "Valve Pressures"))
        self.txt_muscle_0.setText(_translate("MainWindow", "Muscle 0"))
        self.txt_muscle_1.setText(_translate("MainWindow", "Muscle 1"))
        self.txt_muscle_2.setText(_translate("MainWindow", "Muscle 2"))
        self.txt_muscle_3.setText(_translate("MainWindow", "Muscle 3"))
        self.txt_muscle_4.setText(_translate("MainWindow", "Muscle 4"))
        self.txt_muscle_5.setText(_translate("MainWindow", "Muscle 5"))
        self.txt_muscle_6.setText(_translate("MainWindow", "Muscle 5"))
        self.txt_muscle_7.setText(_translate("MainWindow", "Muscle 0"))
        self.txt_muscle_8.setText(_translate("MainWindow", "Muscle 1"))
        self.txt_muscle_9.setText(_translate("MainWindow", "Muscle 3"))
        self.txt_muscle_10.setText(_translate("MainWindow", "Muscle 4"))
        self.txt_muscle_11.setText(_translate("MainWindow", "Muscle 2"))

