# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'common\dynamics_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 440)
        Frame.setStyleSheet("")
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_dynamics = QtWidgets.QFrame(Frame)
        self.frm_dynamics.setGeometry(QtCore.QRect(0, 0, 815, 351))
        self.frm_dynamics.setStyleSheet("background-color: #f0f0f0")
        self.frm_dynamics.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_dynamics.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_dynamics.setObjectName("frm_dynamics")
        self.groupBox = QtWidgets.QGroupBox(self.frm_dynamics)
        self.groupBox.setGeometry(QtCore.QRect(40, 8, 621, 331))
        self.groupBox.setObjectName("groupBox")
        self.sld_x_0 = QtWidgets.QSlider(self.groupBox)
        self.sld_x_0.setGeometry(QtCore.QRect(50, 20, 22, 281))
        self.sld_x_0.setMaximum(150)
        self.sld_x_0.setProperty("value", 100)
        self.sld_x_0.setOrientation(QtCore.Qt.Vertical)
        self.sld_x_0.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sld_x_0.setTickInterval(10)
        self.sld_x_0.setObjectName("sld_x_0")
        self.sld_y_1 = QtWidgets.QSlider(self.groupBox)
        self.sld_y_1.setGeometry(QtCore.QRect(130, 20, 22, 281))
        self.sld_y_1.setMaximum(150)
        self.sld_y_1.setProperty("value", 100)
        self.sld_y_1.setOrientation(QtCore.Qt.Vertical)
        self.sld_y_1.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sld_y_1.setTickInterval(10)
        self.sld_y_1.setObjectName("sld_y_1")
        self.sld_z_2 = QtWidgets.QSlider(self.groupBox)
        self.sld_z_2.setGeometry(QtCore.QRect(210, 20, 22, 281))
        self.sld_z_2.setMaximum(150)
        self.sld_z_2.setProperty("value", 100)
        self.sld_z_2.setOrientation(QtCore.Qt.Vertical)
        self.sld_z_2.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sld_z_2.setTickInterval(10)
        self.sld_z_2.setObjectName("sld_z_2")
        self.sld_roll_3 = QtWidgets.QSlider(self.groupBox)
        self.sld_roll_3.setGeometry(QtCore.QRect(290, 20, 22, 281))
        self.sld_roll_3.setMaximum(150)
        self.sld_roll_3.setProperty("value", 100)
        self.sld_roll_3.setOrientation(QtCore.Qt.Vertical)
        self.sld_roll_3.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sld_roll_3.setTickInterval(10)
        self.sld_roll_3.setObjectName("sld_roll_3")
        self.sld_pitch_4 = QtWidgets.QSlider(self.groupBox)
        self.sld_pitch_4.setGeometry(QtCore.QRect(370, 20, 22, 281))
        self.sld_pitch_4.setMaximum(150)
        self.sld_pitch_4.setProperty("value", 100)
        self.sld_pitch_4.setOrientation(QtCore.Qt.Vertical)
        self.sld_pitch_4.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sld_pitch_4.setTickInterval(10)
        self.sld_pitch_4.setObjectName("sld_pitch_4")
        self.sld_master_6 = QtWidgets.QSlider(self.groupBox)
        self.sld_master_6.setGeometry(QtCore.QRect(560, 20, 22, 281))
        self.sld_master_6.setMaximum(150)
        self.sld_master_6.setProperty("value", 100)
        self.sld_master_6.setOrientation(QtCore.Qt.Vertical)
        self.sld_master_6.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sld_master_6.setTickInterval(10)
        self.sld_master_6.setObjectName("sld_master_6")
        self.sld_yaw_5 = QtWidgets.QSlider(self.groupBox)
        self.sld_yaw_5.setGeometry(QtCore.QRect(450, 20, 22, 281))
        self.sld_yaw_5.setMaximum(150)
        self.sld_yaw_5.setProperty("value", 100)
        self.sld_yaw_5.setOrientation(QtCore.Qt.Vertical)
        self.sld_yaw_5.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.sld_yaw_5.setTickInterval(10)
        self.sld_yaw_5.setObjectName("sld_yaw_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(51, 309, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(133, 310, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(213, 310, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.sld_roll = QtWidgets.QLabel(self.groupBox)
        self.sld_roll.setGeometry(QtCore.QRect(283, 310, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sld_roll.setFont(font)
        self.sld_roll.setAlignment(QtCore.Qt.AlignCenter)
        self.sld_roll.setObjectName("sld_roll")
        self.sld_pitch = QtWidgets.QLabel(self.groupBox)
        self.sld_pitch.setGeometry(QtCore.QRect(364, 310, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sld_pitch.setFont(font)
        self.sld_pitch.setAlignment(QtCore.Qt.AlignCenter)
        self.sld_pitch.setObjectName("sld_pitch")
        self.sld_yaw = QtWidgets.QLabel(self.groupBox)
        self.sld_yaw.setGeometry(QtCore.QRect(443, 310, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sld_yaw.setFont(font)
        self.sld_yaw.setAlignment(QtCore.Qt.AlignCenter)
        self.sld_yaw.setObjectName("sld_yaw")
        self.lbl_master = QtWidgets.QLabel(self.groupBox)
        self.lbl_master.setGeometry(QtCore.QRect(544, 310, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_master.setFont(font)
        self.lbl_master.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_master.setObjectName("lbl_master")
        self.wgt_overlay = QtWidgets.QWidget(self.groupBox)
        self.wgt_overlay.setGeometry(QtCore.QRect(44, 20, 16, 91))
        self.wgt_overlay.setStyleSheet("background-color: rgba(255, 0,0,20)")
        self.wgt_overlay.setObjectName("wgt_overlay")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 125, 31, 16))
        self.label.setObjectName("label")
        self.wgt_overlay_2 = QtWidgets.QWidget(self.groupBox)
        self.wgt_overlay_2.setGeometry(QtCore.QRect(124, 20, 16, 91))
        self.wgt_overlay_2.setStyleSheet("background-color: rgba(255, 0,0,20)")
        self.wgt_overlay_2.setObjectName("wgt_overlay_2")
        self.wgt_overlay_3 = QtWidgets.QWidget(self.groupBox)
        self.wgt_overlay_3.setGeometry(QtCore.QRect(204, 20, 16, 91))
        self.wgt_overlay_3.setStyleSheet("background-color: rgba(255, 0,0,20)")
        self.wgt_overlay_3.setObjectName("wgt_overlay_3")
        self.wgt_overlay_4 = QtWidgets.QWidget(self.groupBox)
        self.wgt_overlay_4.setGeometry(QtCore.QRect(284, 20, 16, 91))
        self.wgt_overlay_4.setStyleSheet("background-color: rgba(255, 0,0,20)")
        self.wgt_overlay_4.setObjectName("wgt_overlay_4")
        self.wgt_overlay_5 = QtWidgets.QWidget(self.groupBox)
        self.wgt_overlay_5.setGeometry(QtCore.QRect(554, 20, 16, 91))
        self.wgt_overlay_5.setStyleSheet("background-color: rgba(255, 0,0,20)")
        self.wgt_overlay_5.setObjectName("wgt_overlay_5")
        self.wgt_overlay_6 = QtWidgets.QWidget(self.groupBox)
        self.wgt_overlay_6.setGeometry(QtCore.QRect(364, 20, 16, 91))
        self.wgt_overlay_6.setStyleSheet("background-color: rgba(255, 0,0,20)")
        self.wgt_overlay_6.setObjectName("wgt_overlay_6")
        self.wgt_overlay_7 = QtWidgets.QWidget(self.groupBox)
        self.wgt_overlay_7.setGeometry(QtCore.QRect(444, 20, 16, 91))
        self.wgt_overlay_7.setStyleSheet("background-color: rgba(255, 0,0,20)")
        self.wgt_overlay_7.setObjectName("wgt_overlay_7")
        self.btn_reload_dynam = QtWidgets.QPushButton(self.frm_dynamics)
        self.btn_reload_dynam.setGeometry(QtCore.QRect(700, 130, 75, 23))
        self.btn_reload_dynam.setObjectName("btn_reload_dynam")
        self.btn_default_dynam = QtWidgets.QPushButton(self.frm_dynamics)
        self.btn_default_dynam.setGeometry(QtCore.QRect(700, 190, 75, 23))
        self.btn_default_dynam.setObjectName("btn_default_dynam")
        self.btn_save_dynam = QtWidgets.QPushButton(self.frm_dynamics)
        self.btn_save_dynam.setGeometry(QtCore.QRect(700, 250, 75, 23))
        self.btn_save_dynam.setObjectName("btn_save_dynam")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.groupBox.setTitle(_translate("Frame", "Ride Intensity"))
        self.label_8.setText(_translate("Frame", "X"))
        self.label_9.setText(_translate("Frame", "Y"))
        self.label_10.setText(_translate("Frame", "Z"))
        self.sld_roll.setText(_translate("Frame", "Roll"))
        self.sld_pitch.setText(_translate("Frame", "Pitch"))
        self.sld_yaw.setText(_translate("Frame", "Yaw"))
        self.lbl_master.setText(_translate("Frame", "Master"))
        self.label.setText(_translate("Frame", "100%"))
        self.btn_reload_dynam.setText(_translate("Frame", "Reload"))
        self.btn_default_dynam.setText(_translate("Frame", "Default"))
        self.btn_save_dynam.setText(_translate("Frame", "Save"))

