# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'space_coaster_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 439)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_input = QtWidgets.QFrame(Frame)
        self.frm_input.setGeometry(QtCore.QRect(5, 4, 791, 351))
        self.frm_input.setStyleSheet("background-color: #f0f0f0")
        self.frm_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_input.setObjectName("frm_input")
        self.btn_dispatch = QtWidgets.QPushButton(self.frm_input)
        self.btn_dispatch.setGeometry(QtCore.QRect(80, 90, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dispatch.setFont(font)
        self.btn_dispatch.setStyleSheet("color:white;background-color: green;")
        self.btn_dispatch.setObjectName("btn_dispatch")
        self.btn_reset_rift = QtWidgets.QPushButton(self.frm_input)
        self.btn_reset_rift.setGeometry(QtCore.QRect(660, 90, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_reset_rift.setFont(font)
        self.btn_reset_rift.setObjectName("btn_reset_rift")
        self.btn_pause = QtWidgets.QPushButton(self.frm_input)
        self.btn_pause.setGeometry(QtCore.QRect(350, 90, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_pause.setFont(font)
        self.btn_pause.setStyleSheet("background-color: orange\n"
"")
        self.btn_pause.setObjectName("btn_pause")
        self.lbl_coaster_status = QtWidgets.QLabel(self.frm_input)
        self.lbl_coaster_status.setGeometry(QtCore.QRect(100, 152, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lbl_coaster_status.setFont(font)
        self.lbl_coaster_status.setObjectName("lbl_coaster_status")
        self.frame = QtWidgets.QFrame(self.frm_input)
        self.frame.setGeometry(QtCore.QRect(90, 200, 671, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_intensity_status = QtWidgets.QLabel(self.frame)
        self.lbl_intensity_status.setGeometry(QtCore.QRect(11, 11, 631, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_intensity_status.setFont(font)
        self.lbl_intensity_status.setObjectName("lbl_intensity_status")
        self.lbl_remote_status = QtWidgets.QLabel(self.frame)
        self.lbl_remote_status.setGeometry(QtCore.QRect(11, 63, 641, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_remote_status.setFont(font)
        self.lbl_remote_status.setObjectName("lbl_remote_status")
        self.lbl_coaster_connection = QtWidgets.QLabel(self.frame)
        self.lbl_coaster_connection.setGeometry(QtCore.QRect(11, 38, 641, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_coaster_connection.setFont(font)
        self.lbl_coaster_connection.setObjectName("lbl_coaster_connection")
        self.lbl_temperature_status = QtWidgets.QLabel(self.frame)
        self.lbl_temperature_status.setGeometry(QtCore.QRect(11, 94, 641, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_temperature_status.setFont(font)
        self.lbl_temperature_status.setObjectName("lbl_temperature_status")
        self.lbl_platform = QtWidgets.QLabel(self.frm_input)
        self.lbl_platform.setGeometry(QtCore.QRect(625, 32, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_platform.setFont(font)
        self.lbl_platform.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_platform.setObjectName("lbl_platform")
        self.btn_exit = QtWidgets.QPushButton(Frame)
        self.btn_exit.setGeometry(QtCore.QRect(640, 390, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.btn_dispatch.setText(_translate("Frame", "Dispatch"))
        self.btn_reset_rift.setText(_translate("Frame", "Reset Rift"))
        self.btn_pause.setText(_translate("Frame", "Pause"))
        self.lbl_coaster_status.setText(_translate("Frame", "Status"))
        self.lbl_intensity_status.setText(_translate("Frame", "Intensity"))
        self.lbl_remote_status.setText(_translate("Frame", "Remote"))
        self.lbl_coaster_connection.setText(_translate("Frame", "Connection"))
        self.lbl_temperature_status.setText(_translate("Frame", "Temperature"))
        self.lbl_platform.setText(_translate("Frame", "Platform"))
        self.btn_exit.setText(_translate("Frame", "Exit"))

