# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModelGui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(600, 450)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 561, 711))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.SerialGroupBox = QtGui.QGroupBox(self.frame)
        self.SerialGroupBox.setGeometry(QtCore.QRect(10, 10, 541, 71))
        self.SerialGroupBox.setObjectName(_fromUtf8("SerialGroupBox"))
        self.frame_2 = QtGui.QFrame(self.SerialGroupBox)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 461, 62))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout = QtGui.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lbl_servo_model = QtGui.QLabel(self.frame_2)
        self.lbl_servo_model.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_servo_model.setObjectName(_fromUtf8("lbl_servo_model"))
        self.gridLayout.addWidget(self.lbl_servo_model, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.btn_serial_connect = QtGui.QPushButton(self.frame_2)
        self.btn_serial_connect.setMinimumSize(QtCore.QSize(80, 20))
        self.btn_serial_connect.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_serial_connect.setStyleSheet(_fromUtf8(" background-color: silver;\n"
"color:black;"))
        self.btn_serial_connect.setObjectName(_fromUtf8("btn_serial_connect"))
        self.gridLayout.addWidget(self.btn_serial_connect, 1, 0, 1, 1)
        self.cmb_servo_model_port = QtGui.QComboBox(self.frame_2)
        self.cmb_servo_model_port.setMinimumSize(QtCore.QSize(80, 20))
        self.cmb_servo_model_port.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cmb_servo_model_port.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.cmb_servo_model_port.setMinimumContentsLength(15)
        self.cmb_servo_model_port.setObjectName(_fromUtf8("cmb_servo_model_port"))
        self.gridLayout.addWidget(self.cmb_servo_model_port, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.MoveGroupBox = QtGui.QGroupBox(self.frame)
        self.MoveGroupBox.setGeometry(QtCore.QRect(10, 90, 541, 131))
        self.MoveGroupBox.setObjectName(_fromUtf8("MoveGroupBox"))
        self.btn_Move = QtGui.QPushButton(self.MoveGroupBox)
        self.btn_Move.setGeometry(QtCore.QRect(32, 30, 50, 23))
        self.btn_Move.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_Move.setObjectName(_fromUtf8("btn_Move"))
        self.frame_5 = QtGui.QFrame(self.MoveGroupBox)
        self.frame_5.setGeometry(QtCore.QRect(120, 20, 411, 101))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.sld_x_0 = QtGui.QSlider(self.frame_5)
        self.sld_x_0.setGeometry(QtCore.QRect(45, 20, 51, 71))
        self.sld_x_0.setMinimum(-100)
        self.sld_x_0.setMaximum(100)
        self.sld_x_0.setSingleStep(10)
        self.sld_x_0.setProperty("value", 0)
        self.sld_x_0.setOrientation(QtCore.Qt.Vertical)
        self.sld_x_0.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sld_x_0.setTickInterval(10)
        self.sld_x_0.setObjectName(_fromUtf8("sld_x_0"))
        self.label_3 = QtGui.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(9, 46, 41, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(5, 80, 46, 13))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(4, 18, 46, 13))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label = QtGui.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(60, 0, 21, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_7 = QtGui.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(125, 0, 21, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.sld_y_1 = QtGui.QSlider(self.frame_5)
        self.sld_y_1.setGeometry(QtCore.QRect(110, 20, 51, 71))
        self.sld_y_1.setMinimum(-100)
        self.sld_y_1.setMaximum(100)
        self.sld_y_1.setSingleStep(10)
        self.sld_y_1.setProperty("value", 0)
        self.sld_y_1.setOrientation(QtCore.Qt.Vertical)
        self.sld_y_1.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sld_y_1.setTickInterval(10)
        self.sld_y_1.setObjectName(_fromUtf8("sld_y_1"))
        self.label_8 = QtGui.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(190, 0, 21, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.sld_z_2 = QtGui.QSlider(self.frame_5)
        self.sld_z_2.setGeometry(QtCore.QRect(175, 20, 51, 71))
        self.sld_z_2.setMinimum(-100)
        self.sld_z_2.setMaximum(100)
        self.sld_z_2.setSingleStep(10)
        self.sld_z_2.setProperty("value", 0)
        self.sld_z_2.setOrientation(QtCore.Qt.Vertical)
        self.sld_z_2.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sld_z_2.setTickInterval(10)
        self.sld_z_2.setObjectName(_fromUtf8("sld_z_2"))
        self.sld_roll_3 = QtGui.QSlider(self.frame_5)
        self.sld_roll_3.setGeometry(QtCore.QRect(240, 20, 51, 71))
        self.sld_roll_3.setMinimum(-100)
        self.sld_roll_3.setMaximum(100)
        self.sld_roll_3.setSingleStep(10)
        self.sld_roll_3.setProperty("value", 0)
        self.sld_roll_3.setOrientation(QtCore.Qt.Vertical)
        self.sld_roll_3.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sld_roll_3.setTickInterval(10)
        self.sld_roll_3.setObjectName(_fromUtf8("sld_roll_3"))
        self.label_10 = QtGui.QLabel(self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(312, 0, 31, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.sld_pitch_4 = QtGui.QSlider(self.frame_5)
        self.sld_pitch_4.setGeometry(QtCore.QRect(305, 20, 51, 71))
        self.sld_pitch_4.setMinimum(-100)
        self.sld_pitch_4.setMaximum(100)
        self.sld_pitch_4.setSingleStep(10)
        self.sld_pitch_4.setProperty("value", 0)
        self.sld_pitch_4.setOrientation(QtCore.Qt.Vertical)
        self.sld_pitch_4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sld_pitch_4.setTickInterval(10)
        self.sld_pitch_4.setObjectName(_fromUtf8("sld_pitch_4"))
        self.sld_yaw_5 = QtGui.QSlider(self.frame_5)
        self.sld_yaw_5.setGeometry(QtCore.QRect(370, 20, 51, 71))
        self.sld_yaw_5.setMinimum(-100)
        self.sld_yaw_5.setMaximum(100)
        self.sld_yaw_5.setSingleStep(10)
        self.sld_yaw_5.setProperty("value", 0)
        self.sld_yaw_5.setOrientation(QtCore.Qt.Vertical)
        self.sld_yaw_5.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sld_yaw_5.setTickInterval(10)
        self.sld_yaw_5.setObjectName(_fromUtf8("sld_yaw_5"))
        self.label_11 = QtGui.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(378, 0, 21, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(250, 0, 31, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.txt_xyzrpy = QtGui.QLineEdit(self.MoveGroupBox)
        self.txt_xyzrpy.setGeometry(QtCore.QRect(0, 60, 121, 20))
        self.txt_xyzrpy.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_xyzrpy.setObjectName(_fromUtf8("txt_xyzrpy"))
        self.btn_reset_xyzrpy = QtGui.QPushButton(self.MoveGroupBox)
        self.btn_reset_xyzrpy.setGeometry(QtCore.QRect(35, 90, 41, 23))
        self.btn_reset_xyzrpy.setObjectName(_fromUtf8("btn_reset_xyzrpy"))
        self.ProgressGroupBox = QtGui.QGroupBox(self.frame)
        self.ProgressGroupBox.setGeometry(QtCore.QRect(10, 230, 541, 41))
        self.ProgressGroupBox.setObjectName(_fromUtf8("ProgressGroupBox"))
        self.progressBar = QtGui.QProgressBar(self.ProgressGroupBox)
        self.progressBar.setGeometry(QtCore.QRect(10, 15, 521, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.TelemetryGroupBox = QtGui.QGroupBox(self.frame)
        self.TelemetryGroupBox.setGeometry(QtCore.QRect(0, 280, 551, 101))
        self.TelemetryGroupBox.setObjectName(_fromUtf8("TelemetryGroupBox"))
        self.frame_4 = QtGui.QFrame(self.TelemetryGroupBox)
        self.frame_4.setGeometry(QtCore.QRect(20, 30, 291, 61))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.cmb_telemetry = QtGui.QComboBox(self.frame_4)
        self.cmb_telemetry.setGeometry(QtCore.QRect(80, 20, 120, 20))
        self.cmb_telemetry.setMinimumSize(QtCore.QSize(120, 20))
        self.cmb_telemetry.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cmb_telemetry.setObjectName(_fromUtf8("cmb_telemetry"))
        self.txt_intensity = QtGui.QLineEdit(self.frame_4)
        self.txt_intensity.setGeometry(QtCore.QRect(230, 20, 30, 20))
        self.txt_intensity.setMinimumSize(QtCore.QSize(30, 20))
        self.txt_intensity.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txt_intensity.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_intensity.setObjectName(_fromUtf8("txt_intensity"))
        self.btn_telemetry = QtGui.QPushButton(self.frame_4)
        self.btn_telemetry.setGeometry(QtCore.QRect(10, 19, 50, 23))
        self.btn_telemetry.setMinimumSize(QtCore.QSize(0, 20))
        self.btn_telemetry.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_telemetry.setObjectName(_fromUtf8("btn_telemetry"))
        self.label_4 = QtGui.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(228, 2, 47, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Platform Test", None))
        self.SerialGroupBox.setTitle(_translate("MainWindow", "Comms", None))
        self.lbl_servo_model.setText(_translate("MainWindow", "Servo Model Port", None))
        self.btn_serial_connect.setText(_translate("MainWindow", "    Connect    ", None))
        self.MoveGroupBox.setTitle(_translate("MainWindow", "Movement Percent", None))
        self.btn_Move.setText(_translate("MainWindow", "Move", None))
        self.label_3.setText(_translate("MainWindow", "0", None))
        self.label_5.setText(_translate("MainWindow", "-100", None))
        self.label_6.setText(_translate("MainWindow", "100", None))
        self.label.setText(_translate("MainWindow", "X", None))
        self.label_7.setText(_translate("MainWindow", "Y", None))
        self.label_8.setText(_translate("MainWindow", "Z", None))
        self.label_10.setText(_translate("MainWindow", "Pitch", None))
        self.label_11.setText(_translate("MainWindow", "Yaw", None))
        self.label_12.setText(_translate("MainWindow", "Roll", None))
        self.txt_xyzrpy.setText(_translate("MainWindow", "0,0,0,0,0,0", None))
        self.btn_reset_xyzrpy.setText(_translate("MainWindow", "Reset", None))
        self.ProgressGroupBox.setTitle(_translate("MainWindow", "Progress", None))
        self.TelemetryGroupBox.setTitle(_translate("MainWindow", "Telemetry File", None))
        self.txt_intensity.setText(_translate("MainWindow", "1.0", None))
        self.btn_telemetry.setText(_translate("MainWindow", "Start", None))
        self.label_4.setText(_translate("MainWindow", "Intensity", None))

